language: generic

services:
- docker

before_install:
  # project unique tools
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"
  - if [[ `npm -v` != 6* ]]; then npm i -g npm@latest; fi

install:
  - meteor npm i

script:
 # Audit npm packages. Fail build whan a PR audit fails, otherwise report the vulnerability and proceed.
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then npx audit-ci --low; else npx audit-ci --low || true; fi || travis_terminate 1
  - npm run lint || travis_terminate 1
  - npm test || travis_terminate 1
  - meteor build --directory .build --architecture=os.linux.x86_64 --server-only
  - export HASH=`git log --pretty=format:'%h' -n 1`
  - docker build --build-arg BUILD_ID=${TRAVIS_BUILD_NUMBER} --build-arg LAST_COMMIT_ID=${HASH} --pull --rm -t "quay.io/razee/razeedash:${TRAVIS_COMMIT}" .
  - if [ -n "${TRAVIS_TAG}" ]; then docker tag quay.io/razee/razeedash:${TRAVIS_COMMIT} quay.io/razee/razeedash:${TRAVIS_TAG}; fi
  - if [ "${TRAVIS_BRANCH}" = "fix_travis" ]; docker tag quay.io/razee/razeedash:${TRAVIS_COMMIT} quay.io/razee/razeedash:${TRAVIS_COMMIT}; fi
  - docker images
  - ./build/process-template.sh kubernetes/razeedash/resource.yaml >/tmp/resource.yaml

before_deploy:
  - docker login -u="${QUAY_ID}" -p="${QUAY_TOKEN}" quay.io

deploy:
  # Deploy master builds
  - provider: script
    script: docker push "quay.io/razee/razeedash:${TRAVIS_COMMIT}"
    skip_cleanup: true
    on:
      branch: master
  - provider: releases
    file: /tmp/resource.yaml
    overwrite: true
    skip_cleanup: true
    prerelease: true
    name: master
    target_commitish: master
    on:
      branch: fix_travis 
    api_key: "${GITHUB_TOKEN}"

  # Deploy alpha builds
  - provider: script
    script: docker push "quay.io/razee/razeedash:${TRAVIS_TAG}"
    skip_cleanup: true
    on:
      tags: true
      condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+_[0-9]{3}$
  - provider: releases
    file: /tmp/resource.yaml
    skip_cleanup: true
    draft: true
    on:
      tags: true
      condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+_[0-9]{3}$
    api_key: "${GITHUB_TOKEN}"

  # Deploy released builds
  - provider: script
    script: docker push "quay.io/razee/razeedash:${TRAVIS_TAG}"
    skip_cleanup: true
    on:
      tags: true
      condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+$
  - provider: releases
    file: /tmp/resource.yaml
    skip_cleanup: true
    on:
      tags: true
      condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+$
    api_key: "${GITHUB_TOKEN}"
